version: '2.4'
services:
  server:
    build:
      context: .\Server\
    hostname: server
    networks:
      - default
  client:
    build:
      context: .\Client\
    networks:
      - default
    environment:
      TARGET_URL: https://server:5000
networks:
  default:
    driver: nat
    ipam:
      config:
        - subnet: 172.18.254.0/24
          aux_addresses:
            server: 172.18.254.1
        