version: '2.4'
services:
  server:
    build:
      context: .\Server\
    hostname: server
    networks:
      net:
        ipv4_address: 172.18.254.10
  client:
    build:
      context: .\Client\
    networks:
      net:
        ipv4_address: 172.18.254.20
    environment:
      TARGET_URL: https://server:5000
networks:
  net:
    driver: nat
    ipam:
      config:
        - subnet: 172.18.254.0/24
          aux_addresses:
            server: 172.18.254.10